---
- hosts: localhost
  connection: local
  gather_facts: False


  tasks:
    
    - name: Test provisioning here
      ec2:
        aws_access_key: 'XXXXXXX'
        aws_secret_key: 'XXXXXXX'
        key_name: ansible
        instance_type: t2.micro
        image: ami-6f68cf0f
        wait: true
        count: 1
        region: us-west-2

...
